# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ed5b2ba76e2959784e7658f9611f95962e90b1a7717f034a8903d7aea801908fa20f0b400f8044803f7ca45996627101b4585e94dee54ea4c891a857229a4471

test:
  secret_key_base: a87f5f5ddce4a02d96d28866a37e22e12c5f36e37cc2080c5c710256a34f96a953465dc702336c866a7607dc7e63592b745e83acd28ab29a1e665fdcd3b8be55

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
